stages:
  - test
  - build
  - deploy

unit-test:
  stage: test
  script: echo 'Testing...!'

unit-build:
  stage: build
  script: echo 'Building...!'

deploy-to-nas:
  stage: deploy
  script: echo 'Deploying...!'